-- White Label package sales/applications, submitted through the public
-- onboarding wizard (WhiteLabelOnboarding.tsx) and reviewed in the admin
-- White Label Packages "Sales" tab. Previously an in-memory-only array in
-- src/app/services/wlPackages.ts, lost on refresh.

CREATE TABLE IF NOT EXISTS public.wl_sales (
  id              TEXT PRIMARY KEY,             -- "WL-001" style, generated by the API
  org             TEXT NOT NULL,
  contact         TEXT NOT NULL,
  email           TEXT NOT NULL,
  package_id      TEXT NOT NULL REFERENCES public.wl_packages(id),
  status          TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('active','pending','suspended','cancelled')),
  users_count     INTEGER NOT NULL DEFAULT 0,
  mrr             NUMERIC(10,2) NOT NULL DEFAULT 0,
  total_paid      NUMERIC(10,2) NOT NULL DEFAULT 0,
  subdomain       TEXT,
  processor       TEXT,
  last_payout_at  TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wl_sales_status ON public.wl_sales(status);

-- Admin/staff-only: RLS enabled, no client-facing policy (service-role bypasses RLS).
-- The public onboarding wizard inserts through the service-role backend route,
-- never a direct client-side write, so no public INSERT policy is needed either.
ALTER TABLE public.wl_sales ENABLE ROW LEVEL SECURITY;
